### ISSUE TITLE
customer/sign_in: missing header CART_ID in api docs

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#785]
When you are anonymous and you put something in the cart you'll get back a CART_ID key for the session.

If you log in - using customer/sign_in - you should pass this key in the headers otherwise the cart won't be assigned to your user.

This is not documented in the customer/sign_in api docs because it relies on the cart service to retrieve the cart.

**Comment by rousseldenis** [comment]
> When you are anonymous and you put something in the cart you'll get back a CART_ID key for the session.
> 
> If you log in - using customer/sign_in - you should pass this key in the headers otherwise the cart won't be assigned to your user.
> 
> This is not documented in the customer/sign_in api docs because it relies on the cart service to retrieve the cart.

@simahawk This is solved using shopinvader_guest_mode.

With this https://github.com/shopinvader/locomotive-shopinvader/blob/v4.0.x/lib/shop_invader/services/erp_service.rb#L194

It returns the good 'customer' key in order to stay 'signed in as guest'.

But you need to change front to implement specific flow for guests.

**Comment by simahawk** [comment]
@rousseldenis I'm talking only about docs. There's no issue w/ the features. I just reported that the CART_ID should included in docs.
