### ISSUE TITLE
[RFC] Multiple carts per user

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#999]
**Requirement:** have the possibility to handle multiple carts per user.
**Use case:** I can prepare different carts for different dates at the same time
**Usage:**
* I can go to `/cart/list` and see the list of my carts
* I can select a cart (call `/cart/select`, change session cart ID)
  * shall we call `customer._assign_cart_and_get_store_cache`? 
  * when the order is selected shall we recompute totals etc? (something might change if I play w/ an order after days)
* I can create a new cart (just flush session cart ID then rely on next `add_item` to create a new one)
* I can delete a cart (call `/cart/delete/$id`)

Any comments / recommendations / remarks?

**Comment by sebastienbeau** [comment]
@thibaultrey

**Comment by thibaultrey** [comment]
In order to respect the plural form already used for sales, addresses etc I think it's more clear to do :
- `/carts/` to get user's carts list,
- `/carts/$id` to get saved cart lines,
- `/carts/$id/select` to select the cart and get it on /cart endpoint
- `/carts/$id/delete` to delete it

For me, plurals nouns give a good overview if this endpoint provides a list or only one item.

**Comment by simahawk** [comment]
I thought to extend the base cart service but it makes sense to add a new one :+1:

**Comment by sebastienbeau** [comment]
It's ok for me
You can do a module "shopinvader_multi_cart"
